### ISSUE TITLE
Parallel execution not working properly 

### ISSUE THREAD

**Issue by rindia** [ManjunathPrabhakar/playwright-java-poc#1]
Both browser consume one element , if one browser instance click login button then another browser shows, login button not found. it should not dependent and should work on two browser.

Failed tests:   runScenario(steps.TestRunner): Error {(..)
  runScenario(steps.TestRunner): Error {(..)

**Comment by codebymad** [comment]
Will check and revert!

**Comment by codebymad** [comment]
Hello - Parallel working without any modifications, here is my log 


`mvn clean verify -Pparallel
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< com.manjunathprabhakar:playwright-demo >---------------
[INFO] Building playwright-demo 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ playwright-demo ---
[INFO] Deleting G:\IntelliJWorkspace\playwright-demo\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ playwright-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ playwright-demo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to G:\IntelliJWorkspace\playwright-demo\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ playwright-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory G:\IntelliJWorkspace\playwright-demo\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ playwright-demo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to G:\IntelliJWorkspace\playwright-demo\target\test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ playwright-demo ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running RunTestparallel

@autoprac
Scenario: Automation Practice Login test1  # src/test/features/automationpractice.feature:9

@autoprac
Scenario: Automation Practice Login test   # src/test/features/automationpractice.feature:4
  Given User Logs in to web page           # stepdefs.AutomationPractice.userLogsInToWebPage()
  Given User Logs in to web page           # stepdefs.AutomationPractice.userLogsInToWebPage()
Success
Expected Black Goat, Found Black Goat
  Then Validate if user name is reflecting # stepdefs.AutomationPractice.validateIfUserNameIsReflecting()
Success
Expected Black Goat, Found Black Goat
  Then Validate if user name is reflecting # stepdefs.AutomationPractice.validateIfUserNameIsReflecting()
Video Path : 891171e240815450ac8da556a52d6de0.webm
Video Path : b41b9b873c4fa6afb43a0763fff786a1.webm
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 64.716 s - in RunTestparallel
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default) @ playwright-demo ---
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ playwright-demo ---
[INFO] Building jar: G:\IntelliJWorkspace\playwright-demo\target\playwright-demo-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- cooker-maven-plugin:3.0.0:cook-report (cooker-reporter-plugin) @ playwright-demo ---
[info] ============== COOKER CUCUMBER REPORT MAVEN PLUGIN STARTED =====================
[info] ========================== By Manjunath Prabhakar ==============================
[info] ======================= ++++ generating started ++++ ===========================
[info] ----------------------------------------
[info] cooker cucumber report parameters
[info] ----------------------------------------
[info] Project Name             : Playwright-java-demo
[info] Show Report on Console   : true
[info] Source JSONs Path        : G:\IntelliJWorkspace\playwright-demo\target\cucumber-reports
[info] Target HTML Path         : G:\IntelliJWorkspace\playwright-demo\target\cooker-reports
[info] Start Page               : [DASHBOARD]
[info] Include Screenshots      : true
[info] Include Fail Screenshots : false
[info] ----------------------------------------
[info] Cooker report generated : G:\IntelliJWorkspace\playwright-demo\target\cooker-reports\cooker_cucumber_report_20_Jan_2022_09_29_55_IST.html
[info] ----------------------------------------------------------
[info] ------------------- Features Overview --------------------
[info] ----------------------------------------------------------
[info] Total Features      : 1
[info] Passed Features     : 1
[info] Failed Features     : 0
[info] Skipped Features    : 0
[info] Other Features      : 0
[info] Feature Pass %      : 100%
[info] Overall Exec Time   : **02m 04s 012ms  Execution time as been combined together, but actual time is below**
[info] ----------------------------------------------------------
[info] ------------------- Scenarios Overview -------------------
[info] ----------------------------------------------------------
[info] Total Scenarios     : 2
[info] Passed Scenarios    : 2
[info] Failed Scenarios    : 0
[info] Skipped Scenarios   : 0
[info] Other Scenarios     : 0
[info] Scenarios Pass %    : 100%
[info] ----------------------------------------------------------
[info] ===================== ++++ generating completed ++++ ===========================
[info] ============== COOKER CUCUMBER REPORT MAVEN PLUGIN ENDED =======================
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  **01:23 min   Actual Execution Time**
[INFO] Finished at: 2022-01-20T09:29:55+05:30
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
`

**Comment by codebymad** [comment]
Feel free to create another issue if needed! Please note parallel execution working without any modifications to the repo.

**Comment by rindia** [comment]
Hi Thanks for quick reply , but i am not able to do parallele execution.
In my case two chromium browser open but one browser 1 is waiting for one element because that element (Login btn) is already click by browser 2

Here is my POM file 

<?xml version="1.0" encoding="UTF-8"?>


<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>


    <groupId>org.example</groupId>
    <artifactId>eSignUI</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M4</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <properties>
        <cucumber.version>6.10.2</cucumber.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.18.0</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-cucumber6</artifactId>
            <version>5.1.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-logback</artifactId>
            <version>5.1.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
            <version>6.1.1</version>
            <scope>test</scope>
        </dependency>


        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>gherkin</artifactId>
            <version>17.0.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.10</version>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>6.10.4</version>
        </dependency>

    </dependencies>
</project>

Test Runner file

package com.esign.steps;


import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;
import org.testng.annotations.DataProvider;

@CucumberOptions(
        features = {"src/test/java/com/features"},
        glue = {"com/steps"}, dryRun = false,
        tags = "@AC_SM_TC_00"
)
public class TestRunner extends AbstractTestNGCucumberTests {
        @Override
        @DataProvider(parallel = true)
        public Object[][] scenarios() {
                return super.scenarios();
        }

}


Hooks file

package com.esign.steps;

import com.esign.base.FrameworkConfig;
import com.esign.base.FrameworkInitalize;
import com.esign.config.ConfigReader;

import com.esign.config.Settings;
import com.esign.locators.ReadLocators;
import io.cucumber.core.logging.Logger;
import io.cucumber.core.logging.LoggerFactory;
import io.cucumber.java.After;
import io.cucumber.java.Before;
import io.cucumber.java.Scenario;

import java.io.IOException;


public class Hooks {
    private static final Logger LOGGER = LoggerFactory.getLogger(Hooks.class);

    @Before
    public void Setup() throws IOException {
        ConfigReader.PopulateSettings();
        Settings.Locators = ReadLocators.readLocatorsProperty();
        FrameworkConfig.LocalPage = new FrameworkInitalize().InitializePlaywright();
    }

//    @AfterStep
//    public void addScreenshotOnFailed(Scenario scenario) {
//        if (scenario.isFailed()) {
//            Allure.addAttachment(scenario.getName(), new ByteArrayInputStream(FrameworkConfig.LocalPage.screenshot()));
//        }
//    }

    @After
    public void cleanUp(Scenario scenario) throws Exception {
        takeScreenshot(scenario);
        FrameworkConfig.LocalPage.close();
        FrameworkConfig.Playwright.close();
    }

    private void takeScreenshot(Scenario scenario) {
        if (scenario.isFailed()) {
            scenario.attach(FrameworkConfig.LocalPage.screenshot(), "image/png", "Screenshot");

        }
    }
}


Error i am getting 

com.esign.steps.TestRunner.runScenario
[ERROR]   Run 1: TestRunner.runScenario » Playwright Object doesn't exist: response@42d946bb383...
[INFO]   Run 2: PASS

**Comment by rindia** [comment]
@ManjunathPrabhakar please help me out from this critical situation

**Comment by codebymad** [comment]
@rindia : this project is working as expected without any changes. It executed in two different threads independently without issues. I could not reproduce the issue you described.

**Comment by rindia** [comment]
@ManjunathPrabhakar , i checked your project and it is fine, but dont know why my customised project is not working

**Comment by codebymad** [comment]
@rindia this project is designed to not use any static variables or methods. This is avoid unnecessary issues when one thread tries to overwrite another. 

If you need each scenarios to be Independent have it own resources, use picocontainer DI and avoid statics
